language: ruby
rvm:
- 2.1

install: gem install bundler && bundle install
script: jekyll build

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages
  - /test-(.*)/

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
